### ISSUE TITLE
`docker exec -it cat /synapse.version` prints out `master` instead of the version

### ISSUE THREAD

**Issue by jhamfler** [silvio/docker-matrix#2]
Does the docker image always contain the newest synapse when I build a new image out of your repo?
Using `docker exec -it cat /synapse.version` says that I am on `master` but not where the HEAD is or which version. So I could be an an old master, right?

**Comment by silvio** [comment]
right! It is gone as I remove the git dependency.
I will fix this

**Comment by jhamfler** [comment]
Wow what a fast answer. Thank you very much for your help!

**Comment by jhamfler** [comment]
I have another question related to it:
How can I upgrade to Synapse 0.13.x?

`docker logs CONTAINERID 2>&1 |grep Synapse|grep version` shows version 0.12.0

**Comment by silvio** [comment]
@jhamfler  I think the version output string has changed. Try to use `docker logs CONTAINERID 2>&1 | grep -i "Server version"`.

**Comment by silvio** [comment]
@jhamfler ... and you have to pull the new images via `docker pull silviof/docker-matrix`.

**Comment by jhamfler** [comment]
I removed the whole image and downloaded it again a few days ago to have everything clean. It works well, thank you for your help!
