### ISSUE TITLE
Cannot create pid file: /var/run/turnserver.pid:

### ISSUE THREAD

**Issue by caplod** [silvio/docker-matrix#23]
I just updated to the latest docker image.
now I got this error. `Cannot create pid file: /var/run/turnserver.pid: Permission denied`

my turnsserver.conf looks like this:

```
lt-cred-mech
use-auth-secret
static-auth-secret=<secret>
realm=<myurl>
cert=/data/<myurl>.tls.crt
pkey=/data/<myurl>.tls.key
```

how can I fix this?

**Comment by silvio** [comment]
You cannot.
I have to fix this. I will do this today.

Thanks for the report!
