### ISSUE TITLE
Permission errors /homeserver.log

### ISSUE THREAD

**Issue by williamboman** [silvio/docker-matrix#24]
Hi, I'm running into permission errors when building against the `release-0.19.2` synapse branch.

Logs are saying;
```sh
ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/homeserver.log'
```

Temporarily fixed it by;

```sh
$ docker exec synapse touch /homeserver.log
$ docker exec synapse chmod 0666 /homeserver.log
```

**Comment by douglas-lee** [comment]
i found the same error.

**Comment by williamboman** [comment]
I've worked around this by adding `touch /homeserver.log && chmod 0666 /homeserver.log` to the `RUN` directive in `Dockerfile`. Maybe `(umask 01 && touch /homeserver.log)` is cleaner. I don't feel confident that's a proper solution though so I'm hesitant to opening a PR with that fix.

**Comment by silvio** [comment]
this is bad. The same build is running on my server without problems.

I will fix this in in the evening or someone of you want to contribute a solution?

**Comment by williamboman** [comment]
Running `docker exec <container> /start.sh generate` fixes this, as it'll configure the log file to be under `/data`. (when are you supposed to run the `generate` subcommand?)

**Comment by silvio** [comment]
Since 141a4d0fce a freshly generated configuration has a fix for a wrong configured logfile. Bad: previous generated configfiles are wrong configured.
Can you try to fix your settings on `homeserver.yaml` (`log_file` and `log_config` parameters) and in `${SERVERNAME}.log.config` (`filename` parameter)?

**Comment by silvio** [comment]
ping @williamboman and @douglas-lee

**Comment by williamboman** [comment]
I fixed this by running the `generate` sub-command in a container that mounts a data volume, so the changes are persistent.

**Comment by silvio** [comment]
okay, thanks @williamboman
