### ISSUE TITLE
Feature request: Log to STDOUT

### ISSUE THREAD

**Issue by dm-coding** [silvio/docker-matrix#26]
Following principle 11 of the 12 Factor App, it's widely believed that good docker apps should treat logs as event streams by writing them to STDOUT, not to a file. If this feature is available for matrix, it's somewhat badly documented. I'd like to request that the default log options for this container be to write the log to STDOUT where they will be automatically collected by the docker daemon, not to a file.

**Comment by silvio** [comment]
Its configurable. Per default we log to console AND to file. You can disable logging to file via changing of options in your `${SERVER}.log.config` file. On the `root` entity in this file you can remove the `file` option at `handlers` entry.

Is this what you want?

**Comment by dm-coding** [comment]
Yep, that's perfect. Thank you very much. However I wasn't able to find documentation about that so I guess my feature request would be to disable logging on file by default or to document that feature better in readme. (We managed to lose a server over the weekend due to running out of space because of the file log so its not just a theoretical concern :-) ;-).)

**Comment by silvio** [comment]
The `${SERVER}.log.config` is created at config generation time. Unfortunately `synapse` has no option to change the log config settings, so its not possible to generate a logfile with your needs.

But, I welcome your contributions if you have something for me :-)
