### ISSUE TITLE
use tagging

### ISSUE THREAD

**Issue by Finkregh** [silvio/docker-matrix#27]
It would be nice if you could tag the docker-file according to the matrix-releases

(thanks for your work so far :heart: )

**Comment by silvio** [comment]
The complete dockerfile should be done in the main repositories of the matrix-ecosystem. The tag should be done there and not here.

**Comment by Finkregh** [comment]
yes, should be done there, but also here (in the Dockerfile)...
You could use the VERSION directive and use that in the git clone, as far as i know...

like that you could switch between versions via docker-tags...
