### ISSUE TITLE
TURN server udp port range and external IP

### ISSUE THREAD

**Issue by mvgorcum** [silvio/docker-matrix#29]
If you want the TURN part of coturn to work you'll need to forward the udp portrange.
By default that is 49152-65535/udp but it's configurable in turnserver.conf with min-port=XXX and max-port=XXX

You might also have to configure the external ip address in turnserver.conf with external-ip=XX.XX.XX.XX

STUN works fine with the config described in the readme, though. Maybe this can be put in the readme.

**Comment by silvio** [comment]
Hi @mvgorcum, can you document this?

**Comment by mvgorcum** [comment]
Sure, I'll make a pull request soonish.

On June 15, 2017 5:15:58 PM GMT+02:00, silvio <notifications@github.com> wrote:
>Hi @mvgorcum, can you document this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/silvio/docker-matrix/issues/29#issuecomment-308769666

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by silvio** [comment]
Closed with #31
