### ISSUE TITLE
Missing email templates / won't start since 0.22

### ISSUE THREAD

**Issue by tribut** [silvio/docker-matrix#35]
Upgrading results in a startup error:

    jinja2.exceptions.TemplateNotFound: notif_mail.html

Creating a clone of the synapse repo in the data dir and changing the path of `email/template_dir` in homeserver.yaml fixes this, so I guess the file is missing from the image somehow?

**Comment by tribut** [comment]
See https://github.com/matrix-org/synapse/issues/2331 for context.

**Comment by almereyda** [comment]
@tribut Thanks for the tip with the clone of the repository in the data folder. This and [setting a full path into `template_dir` in `homeserver.yaml`](https://github.com/matrix-org/synapse/issues/2331#issuecomment-312904177) helped resolving the issue for me (temporarily).

**Comment by silvio** [comment]
Hmm, I don't have the problem with a new installation and not with a running installation (upgraded docker image). How can I trigger this problem? The `email:`-part in my configuration is enabled.

**Comment by almereyda** [comment]
This seems to be related to how synapse and pip interact, eventually is the package broken and only partly released?. https://github.com/matrix-org/synapse/issues/2331#issuecomment-337207086

**Comment by andreaspeters** [comment]
This issue dont exist anymore. But if u still have it, please reopen.
