### ISSUE TITLE
Synapse v0.23.1 won't start due to pyopenssl

### ISSUE THREAD

**Issue by mvgorcum** [silvio/docker-matrix#41]
It errors out with:
`Missing Requirement: Can't import 'OpenSSL' which is part of 'pyopenssl>=0.14' 
To install run: 
    pip install --upgrade --force "pyopenssl>=0.14"`

After running:  
`pip install --upgrade --force "pyopenssl>=0.14"  `
in the container it did start fine.

**Comment by dva-re** [comment]
Does the current image from dockerhub work properly now? Can we update to the current version?

**Comment by mvgorcum** [comment]
As far as I know the current image on dockerhub will fail with this error. If you did update you should be able to fix it with:  
`docker exec CONTAINERID pip install --upgrade --force "pyopenssl>=0.14"`  
Though I did it by first running bash inside the container.

So you can update if you want, but you'll have to manually install pyopenssl in the container.

**Comment by silvio** [comment]
Thanks @mvgorcum, I have seen the problems at #42, you are still working on this issue?

**Comment by mvgorcum** [comment]
Yes, I am (was?) still working on it. I think I found the issue.
