### ISSUE TITLE
We are interesting to maintain your project.

### ISSUE THREAD

**Issue by andreaspeters** [silvio/docker-matrix#47]
Hi Silvio,

we already had a contact via a github issue and pull request. I just
read u can not maintain your docker-matrix anymore. Sorry to hear that,
but I know it from myself, life is changing and sometimes sth happend
that u will not have the time anymore. Well, if u like, my company can
maintain your project for u. Actually we already fork it some months
ago, (https://github.com/AVENTER-UG/docker-matrix) but I think the best
would be to fork it again.

So, hope u will warm with it, take your time to think about it.

Regards,
Andreas

**Comment by andreaspeters** [comment]
We start to maintain docker-matrix unofficial. Hopefully silvio is fine with that! https://github.com/AVENTER-UG/docker-matrix

**Comment by mvgorcum** [comment]
Assuming you're going to take up the mantle you should probably open the issues on your fork and update the docker hub image to 0.26 (which is released now)

**Comment by andreaspeters** [comment]
Done. :-) https://hub.docker.com/r/avhost/docker-matrix/builds/

**Comment by silvio** [comment]
Sorry - some time problems on my side.

You can maintain this project. But one thing is important: be compatible to running setups. I will give you access to this repository and that one on hub.docker.com.

**Comment by silvio** [comment]
@andreaspeters : have you an id for hub.docker.com?

**Comment by mvgorcum** [comment]
@silvio Thank you for all the work you put in to maintaining the docker-matrix image. I hope everything goes well with how busy you are.

**Comment by andreaspeters** [comment]
Thanks @silvio, I will care your baby like its my own one. I'm sure @mvgorcum will keep a eye on me. :-) hope u will be fine soon.

my organization id is "avhost" my private one "andreaspeters". If you can give access to my company, it would be great.

**Comment by silvio** [comment]
Hi @andreaspeters, thanks for taking over. It's not possible to add a company as contributor on dockerhub and github. So I have added just you as contributor.

Can you test the accessibility on both systems?

**Comment by andreaspeters** [comment]
Your welcome. :-)

github is working. 

```
➜  docker-matrix git:(master) ✗ git commit -am "small test change to check the credential"
[master f8fedc2] small test change to check the credential
 1 file changed, 2 insertions(+)
➜  docker-matrix git:(master) git push
Enter passphrase for key '#': 
Zähle Objekte: 3, Fertig.
Delta compression using up to 4 threads.
Komprimiere Objekte: 100% (3/3), Fertig.
Schreibe Objekte: 100% (3/3), 312 bytes | 312.00 KiB/s, Fertig.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:silvio/docker-matrix.git
   fa8c2fe..f8fedc2  master -> master
➜  docker-matrix git:(master) 
```

**Comment by andreaspeters** [comment]
on docker hub I didnt got a invitation and I also cannot see that I have rights on your repo.

**Comment by silvio** [comment]
Hmm, I have added you as contributor to the repository "https://hub.docker.com/r/silviof/docker-matrix/". I will look into this issue in the evening.

**Comment by andreaspeters** [comment]
now I see that I contribute your docker repo. :-) well, like u see on our docker repo (https://hub.docker.com/r/avhost/docker-matrix/tags/), we include docker images with the matrix version. so, for the first moment we will update your and our docker-matrix repo on docker hub.

**Comment by silvio** [comment]
Thanks @andreaspeters to take over this project. I don't know what you can see and do as a contributor. Be aware it is a webhook activated which will generate a new docker-image on dockerhub on all changes to master branch.

Happy hacking,
Silvio

**Comment by andreaspeters** [comment]
we have to thank u @silvio :-)

As I can see, I have no access to your repo. https://travis-ci.org/AVENTER-UG/docker-matrix/builds/327447714

```
1.34s$ docker push silvio/docker-matrix:test
The push refers to a repository [docker.io/silvio/docker-matrix]
b1d2c244c541: Preparing
d57506e7d5b5: Preparing
064fdbf37604: Preparing
7ff7783df670: Preparing
6f63f51a02cb: Preparing
f04dfc518748: Preparing
f04dfc518748: Waiting
denied: requested access to the resource is denied
```

I dont want to break the master, thats why I ever decide also to create docker images with a version number. :-) we are using matrix in a production system. So, I'm very careful and nervous. :-)

**Comment by andreaspeters** [comment]
vielleicht ist es ja sinnvoller du deaktiviert das repo innerhalb von travis. bei einem zukuenftigen pull request werde ich meine travis.yml mit mergen. dies wuerde in deinem travis account aber zu fehlern fuehren. was denkst du?

**Comment by silvio** [comment]
Yea, I have deactivated the travis service.
