### ISSUE TITLE
Several high vulnerabilities reported by "clair"

### ISSUE THREAD

**Issue by ulope** [silvio/docker-matrix#53]
The linked "clair" travis ci job shows several (17 currently) severity level `high` vulnerabilities to be present in the docker image. 
This seems concerning. If it's not then there should be an explanation why.

**Comment by andreaspeters** [comment]
that's security issues in the os inside of the docker image. There is no way that we will describe, inform or rate everyone. But Clair give out the cve numbers. Everybody have to research byself to see if it could be an impact. Sorry for that but secop is a fulltime job we cannot pay at the moment. :-(

**Comment by andreaspeters** [comment]
that's security issues in the os inside of the docker version. There is no way that we will describe, inform or rate everyone. But Clair give out the cve numbers. Everybody have to research byself to see if it could be an impact. Sorry for that but secop is a fulltime job we cannot pay at the moment. :-(

**Comment by andreaspeters** [comment]
But, we can write into the readme, that Clair just scan the os and not matrix. Maybe thats a good idea. So, thanks @ulope 😃

**Comment by andreaspeters** [comment]
we add a advice to the readme. in the next push it will be online.
