### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dest4** [silvio/docker-matrix#55]
Hi, thanks for your work.
I did not see any software license applied to this repo. Do you plan to add one?

**Comment by andreaspeters** [comment]
Your welcome. 

Thats a good question. I have to talk with @silvio about it. Its his baby, so he have to choose. :-)

**Comment by silvio** [comment]
ohh hmm, I never have think about licences. Maybe GPLv2. Other options possible here? @andreaspeters what do you think?

**Comment by andreaspeters** [comment]
Actually I'm always using GPL v3. But 2 is OK too. So if its OK for u, I will add a license file to this repo. 😃

**Comment by silvio** [comment]
Yeah, I'm oldschool and have no references on this topic for this files. Let us use GPLv2. Thanks @andreaspeters

**Comment by andreaspeters** [comment]
Great, thanks 😃

**Comment by andreaspeters** [comment]
in the next push the license will be inside.
