### ISSUE TITLE
contact to you silvio :-)

### ISSUE THREAD

**Issue by andreaspeters** [silvio/docker-matrix#62]
Hi Silvio,
hast Du ein liberapay account? Wir haben dort ein docker-matrix team eingerichtet und ich würde Dich dem gerne hinzufügen. Des weiteren wäre es schön wenn wir noch einen anderen weg hätten um in kontakt zu kommen. Du kannst Dich ja mal via "https://matrix.aventer.biz/#/room/#avEnterSupport:matrix.aventer.biz" melden, wenn Du lust hast.

Viele Grüße,
Andreas

**Comment by silvio** [comment]
Hi, yoo - ich komm ma' rum ...
