### ISSUE TITLE
Slight Rework of Container Startup

### ISSUE THREAD

**Issue by benyanke** [silvio/docker-matrix#67]
The process of having to run 'generate', then 'start' argument is subpar for many docker workflows.

Would you be open to a PR which would allow the image to be run without any commands?

This would run generate once, then run the start command every time after that - a flag would be set in the config directory to note that generate has already run.

Currently, this wouldn't be usable with how I run docker on my server, but with this minor PR, it would work wonderfully with my workflow, as well as how I know many others use it.

**Comment by andreaspeters** [comment]
hi @benyanke, actually we are running it without a command too. we mounting the directory with the configuration file inside of the container. and its working very well. :-)

**Comment by mvgorcum** [comment]
I hope [this](https://github.com/AVENTER-UG/docker-matrix/pull/16) PR solves the issue. If you have a better idea please let me know.

Do note that, as @andreaspeters mentioned, the docker by default runs the 'start' argument if you don't supply one yourself. Either way, with this solution you'll still have to run the container twice, once to generate and review the config files, and once to actually start synapse.

This is done specifically to keep the container backwards compatible.

**Comment by benyanke** [comment]
Closing out this issue, since the PR (#16) solves the problem I'm interested in - at this point, they're duplicate threads.

Let's continue to discuss on the PR, which includes both the problem *and* my proposed solution (thanks @mvgorcum - you beat me to it)
