### ISSUE TITLE
Upgrade to 0.32.1

### ISSUE THREAD

**Issue by dajohi** [silvio/docker-matrix#69]
https://matrix.org/blog/2018/07/06/security-update-synapse-0-32-0/

**Comment by mvgorcum** [comment]
The upgrade from 0.32.0 to 0.32.1 only adds a dependency that is already met in the container image, so the upgrade doesn't change anything other than the version number.

However, 0.32.2 is out already, and that one is available on [docker-hub ](https://hub.docker.com/r/avhost/docker-matrix/tags/).

Also note that docker-matrix is currently being tracked [here](https://github.com/AVENTER-UG/docker-matrix).

**Comment by andreaspeters** [comment]
I merge it with our main repo. Like @mvgorcum already said, the repo and the docker-hub changed.
