### ISSUE TITLE
Force a image rebuild

### ISSUE THREAD

**Issue by ogarcia** [silvio/docker-matrix#9]
Hi,

After the last [critical security vulnerability in Synapse](https://matrix.org/blog/2016/07/08/critical-security-vulnerability-in-synapse-0-12-to-0-16-1-inclusive/) I think that must delete all older docker builds in DockerHub and force to build a new one.

Greetings.

**Comment by silvio** [comment]
Hi @ogarcia ,

thank you for your hint. I have started a rebuiid. It's done now.
